# Generated by Django 2.2.2 on 2020-02-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_essays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(max_length=200)),
                ('SubSection', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('article', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Essays',
        ),
    ]
